In [1]:
import pandas as pd
import numpy as np


from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score

In [2]:
DATA_JSON_FILE = '2.1 SpamData/01_Processing/email-text-data.json'

In [3]:
data = pd.read_json(DATA_JSON_FILE)

In [4]:
data.tail()

,MESSAGE,CATEGORY,FILE_NAME
5790,"I'm one of the 30,000 but it's not working ver...",0,00609.dd49926ce94a1ea328cce9b62825bc97
5791,Damien Morton quoted:\n\n>W3C approves HTML 4 ...,0,00957.e0b56b117f3ec5f85e432a9d2a47801f
5792,"On Mon, 2002-07-22 at 06:50, che wrote:\n\n\n\...",0,01127.841233b48eceb74a825417d8d918abf8
5793,"Once upon a time, Manfred wrote :\n\n\n\n> I w...",0,01178.5c977dff972cd6eef64d4173b90307f0
5794,"If you run Pick, and then use the ""New FTOC"" b...",0,00747.352d424267d36975a7b40b85ffd0885e

In [5]:
data.shape

(5795, 3)

In [6]:
data.sort_index(inplace=True)

In [7]:
data.tail()

,MESSAGE,CATEGORY,FILE_NAME
5790,"I'm one of the 30,000 but it's not working ver...",0,00609.dd49926ce94a1ea328cce9b62825bc97
5791,Damien Morton quoted:\n\n>W3C approves HTML 4 ...,0,00957.e0b56b117f3ec5f85e432a9d2a47801f
5792,"On Mon, 2002-07-22 at 06:50, che wrote:\n\n\n\...",0,01127.841233b48eceb74a825417d8d918abf8
5793,"Once upon a time, Manfred wrote :\n\n\n\n> I w...",0,01178.5c977dff972cd6eef64d4173b90307f0
5794,"If you run Pick, and then use the ""New FTOC"" b...",0,00747.352d424267d36975a7b40b85ffd0885e

In [8]:
vectorizer = CountVectorizer(stop_words='english')

In [9]:
all_features = vectorizer.fit_transform(data.MESSAGE)

In [10]:
all_features.shape

(5795, 102512)

In [11]:
vectorizer.vocabulary_

{'dear': 32664,
 'homeowner': 47966,
 'rates': 76257,
 'lowest': 59288,
 'point': 72205,
 '40': 7778,
 'years': 98324,
 'help': 47132,
 'best': 23080,
 'rate': 76254,
 'situation': 82203,
 'matching': 60849,
 'needs': 64666,
 'hundreds': 48538,
 'lenders': 57945,
 'home': 47938,
 'improvement': 51329,
 'refinance': 76979,
 'second': 80863,
 'mortgage': 62943,
 'equity': 38930,
 'loans': 58982,
 'perfect': 70389,
 'credit': 30920,
 'service': 81253,
 '100': 1455,
 'free': 42708,
 'owners': 68628,
 'new': 64903,
 'buyers': 25564,
 'obligation': 66726,
 'just': 54974,
 'quick': 75454,
 'simple': 82057,
 'form': 42361,
 'jump': 54925,
 'start': 84010,
 'future': 43265,
 'plans': 71847,
 'today': 87910,
 'visit': 92787,
 'http': 48428,
 '61': 10046,
 '145': 2232,
 '116': 1831,
 '186': 2705,
 'user0201': 91206,
 'index': 51568,
 'asp': 20381,
 'afft': 17558,
 'qm10': 75015,
 'unsubscribe': 90823,
 'light': 58396,
 'watch': 94147,
 'attention': 20691,
 'computer': 29700,
 'users': 91234,
 'special': 83376,
 'package': 69032,
 'deal': 32648,
 'norton': 65746,
 'systemworks': 85615,
 '2002': 3465,
 'software': 82971,
 'suite': 84883,
 'professional': 73272,
 'edition': 37496,
 'includes': 51458,
 'yes': 98372,
 'feature': 40997,
 'packed': 69040,
 'utilities': 91340,
 'low': 59278,
 'price': 73044,
 'protect': 73519,
 'unwanted': 90879,
 'hazardous': 46795,
 'viruses': 92753,
 'secure': 80907,
 'private': 73136,
 'valuable': 91923,
 'information': 51802,
 'allow': 18674,
 'transfer': 88426,
 'files': 41477,
 'send': 81073,
 'mails': 60324,
 'safely': 79976,
 'backup': 22142,
 'data': 32264,
 'easily': 37216,
 'improve': 51326,
 'pc': 69668,
 'performance': 70397,
 'superior': 84997,
 'integral': 52201,
 'diagnostics': 33839,
 'great': 45499,
 '300': 5548,
 'combined': 29369,
 'retail': 77862,
 'value': 91926,
 '29': 4747,
 '99': 13922,
 'shipping': 81668,
 'don': 34934,
 'fall': 40553,
 'prey': 73038,
 'destructive': 33376,
 'hackers': 46378,
 'delay': 32992,
 'copy': 30400,
 'euro': 39362,
 'specialdiscounts4u': 83378,
 'com': 29350,
 'email': 38156,
 'screened': 80641,
 'filtered': 41512,
 'house': 48194,
 'opt': 67808,
 'compliance': 29625,
 'state': 84046,
 'laws': 57594,
 'wish': 95555,
 'mailing': 60301,
 'lists': 58657,
 'thousands': 87291,
 'providers': 73571,
 'dvd': 36500,
 'optoutd': 67866,
 'html': 48403,
 'multi': 63546,
 'message': 61597,
 'mime': 62057,
 'format': 42371,
 '_nextpart_000_1cdc19_01c25366': 15017,
 '4b57f3a0': 8400,
 'content': 30194,
 'type': 89241,
 'text': 86862,
 'plain': 71820,
 'charset': 27742,
 'windows': 95468,
 '1252': 1983,
 'encoding': 38412,
 'quoted': 75522,
 'printable': 73100,
 'dare': 32220,
 'try': 88784,
 'better': 23128,
 'annuity': 19324,
 '20': 3443,
 'guaranteed': 45806,
 '0a': 909,
 'year': 98317,
 'surrender': 85125,
 'charge': 27722,
 'agent': 17719,
 'commission': 29454,
 'age': 17701,
 '80': 11972,
 '09': 840,
 '800': 11973,
 '888': 12786,
 '7641': 11337,
 'ext': 39961,
 '103': 1587,
 'mail': 60233,
 'phone': 71219,
 'city': 28328,
 'pmg': 72075,
 'financial': 41535,
 'services': 81255,
 'deposits': 33212,
 '000': 1,
 '25': 4389,
 'totalling': 88140,
 '999': 13973,
 'want': 94025,
 'receive': 76690,
 'mailings': 60305,
 'does': 34833,
 'communication': 29495,
 'sent': 81117,
 'insurance': 52176,
 'professionals': 73277,
 'removed': 77387,
 'list': 58604,
 'reply': 77524,
 'instead': 52131,
 'www': 96395,
 'insuranceiq': 52177,
 'optout': 67863,
 'legal': 57888,
 'notice': 65801,
 'insiq': 52063,
 'htm': 48400,
 'iso': 53020,
 '8859': 12780,
 'head': 46943,
 'title': 87596,
 'meta': 61618,
 'equiv': 38931,
 '3d': 6339,
 '3diso': 7004,
 'body': 24340,
 'bgcolor': 23248,
 '666666': 10342,
 '000000': 4,
 'font': 42193,
 'face': 40438,
 'arial': 20068,
 'helvetica': 47152,
 'sans': 80153,
 'serif': 81198,
 'table': 85992,
 'width': 95353,
 '550': 9191,
 'border': 24531,
 'align': 18586,
 'center': 27351,
 'cellpadding': 27321,
 'cellspacing': 27329,
 'bordercolor': 24534,
 'ffffff': 41261,
 'tr': 88312,
 'td': 86420,
 'img': 51142,
 'src': 83747,
 'iiq': 50827,
 'images': 51097,
 '20020822': 3530,
 '101': 1508,
 'gif': 44578,
 'alt': 18755,
 'height': 47089,
 '55': 9190,
 'br': 24763,
 '102': 1532,
 'jpg': 54708,
 '47': 8201,
 '248': 4346,
 '201': 3627,
 '32': 5709,
 '142': 2212,
 '202': 3643,
 '10': 1454,
 '508': 8943,
 'size': 82232,
 '535': 9097,
 '115': 1815,
 '95': 13739,
 'method': 61654,
 'post': 72498,
 'action': 16850,
 '65': 10240,
 '217': 3918,
 '159': 2393,
 'response': 77776,
 'background': 22105,
 'colspan': 29335,
 '15': 2296,
 'right': 78326,
 'input': 51998,
 'contactname': 30159,
 '50': 8880,
 'rowspan': 78956,
 'valign': 91912,
 'middle': 61939,
 'q3': 74435,
 '43': 8001,
 '30': 5547,
 'nbsp': 64477,
 'submit': 84685,
 'btnsubmit': 25240,
 'hidden': 47438,
 'hdnrecipienttxt': 46912,
 'rhock': 78217,
 'pmgsecurities': 72078,
 'hdnsubjecttxt': 46913,
 'ad': 16925,
 'inquiry': 52011,
 'sentto': 81129,
 '304704': 5577,
 '416': 7919,
 'cccccc': 27087,
 'href': 48321,
 'important': 51286,
 'domain': 34898,
 'names': 64284,
 'finally': 41528,
 'available': 20998,
 'general': 44173,
 'public': 73920,
 'discount': 34213,
 'prices': 73051,
 'register': 77080,
 'exciting': 39654,
 'biz': 23704,
 'info': 51763,
 'original': 68025,
 'net': 64784,
 '14': 2181,
 'brand': 24822,
 'extensions': 39977,
 'recently': 76707,
 'approved': 19789,
 'icann': 49631,
 'rights': 78337,
 'biggest': 23512,
 'benefit': 22989,
 'course': 30628,
 'currently': 31378,
 'easier': 37213,
 'attractive': 20714,
 'easy': 37230,
 'remember': 77331,
 'affordable': 17553,
 'domains': 34907,
 'registration': 77090,
 'fees': 41048,
 'include': 51456,
 'access': 16607,
 'use': 91183,
 'control': 30280,
 'panel': 69221,
 'manage': 60512,
 'sincerely': 82093,
 'administrator': 17157,
 'remove': 77372,
 'address': 17047,
 'promotional': 73400,
 'company': 29524,
 'click': 28665,
 'centralremovalservice': 27366,
 'cgi': 27559,
 'bin': 23577,
 'g1': 43497,
 'ss2': 83790,
 '5592oxer3': 9228,
 '424uqkh2259kcdl5': 7971,
 '189geil31': 2732,
 'line': 58492,
 'away': 21194,
 'cd': 27152,
 'people': 70352,
 'like': 58425,
 'month': 62825,
 'let': 58007,
 'talk': 86128,
 'product': 73245,
 'samples': 80092,
 'earn': 37188,
 '45': 8104,
 'days': 32367,
 'think': 87198,
 'kidding': 56005,
 'earned': 37190,
 'precisely': 72799,
 '26': 4494,
 '087': 804,
 '58': 9326,
 '94': 13701,
 'doing': 34869,
 'scanned': 80399,
 'checks': 27823,
 'online': 67578,
 'eyes': 40077,
 've': 92148,
 'tweaked': 89111,
 'things': 87195,
 'little': 58689,
 'busy': 25526,
 'aren': 20034,
 'good': 45170,
 'talking': 86134,
 'work': 95897,
 'time': 87496,
 'helped': 47134,
 'julie': 54913,
 '750': 11270,
 'week': 94953,
 'jeff': 54017,
 '6500': 10242,
 'weeks': 94962,
 'exact': 39581,
 'business': 25500,
 'plan': 71828,
 'tell': 86645,
 'exactly': 39582,
 'expect': 39824,
 'starting': 84014,
 'guesswork': 45840,
 'seriously': 81201,
 'evaluate': 39402,
 'happy': 46586,
 'fly': 42003,
 'los': 59214,
 'angeles': 19195,
 'expense': 39847,
 'closer': 28771,
 'look': 59144,
 'following': 42169,
 'postal': 72502,
 'number': 66159,
 'area': 20023,
 'code': 29147,
 'mailto': 60332,
 'cashflows99': 26846,
 'excite': 39650,
 'subject': 84662,
 'free_cd': 42715,
 'senate': 81069,
 '1618': 2434,
 'section': 80893,
 '301': 5561,
 'states': 84059,
 'statement': 84057,
 'transmissions': 88473,
 'unsolicited': 90807,
 'commercial': 29443,
 'electronic': 38011,
 'recipient': 76734,
 'person': 70515,
 'initiates': 51905,
 'transmission': 88472,
 'stopped': 84328,
 'cost': 30523,
 'sending': 81087,
 'originating': 68033,
 'word': 95881,
 '_nextpart_000_00b8_51e06b6a': 14954,
 'c8586b31': 26268,
 'base64': 22438,
 'sgvyzsdzihrozsbob3r0zxn0ihroaw5nigluierwrhmuie5vdyb5b3ugy2fu': 81458,
 'ig1ha2ugysbwzxjzb25hbcbiywnrdxancmnvchkgb2ygysbevkqgcmlnahqg': 50278,
 'b250bybdrc1sliagt3vyicjib3qiig5ldybzb2z0d2fyzsblyxnpbhkgdgfr': 21636,
 'zxmgew91ihrocm91z2gncnrozsbzdgvwcyb0bybtywtligegy29wesbvzib5': 101108,
 'b3vyig93bibevkrzlg0kdqpot1cgsu5dtfveruqgrk9siezsruuhienvchkg': 21874,
 'uexbwvnuqvrjt04sie1vu0ldl01qm3mgyw5kigfsbcbtb2z0d2fyzs4ncg0k': 89776,
 'lsbtdgvwigj5ifn0zxagsw50zxjhy3rpdmugsw5zdhj1y3rpb25zia0klsbb': 59447,
 'bgwgu29mdhdhcmugvg9vbhmgsw5jbhvkzwqgt24gq0qgdqotie5vierwrcbc': 23338,
 'dxjuzxigumvxdwlyzwqgdqotiezsruugtgl2zsbuzwnobmljywwgu3vwcg9y': 36649,
 'dcanci0gmzagrgf5ifjpc2sgrnjlzsbucmlhbcbbdmfpbgfibgugdqotiezs': 32463,
 'ruugrhzkie1vdmllig9mihlvdxigy2hvawnlichmsu1jveveifrjtuugt0zg': 79410,
 'rvihkq0kdqpxzsboyxzliefsbcb0agugc29mdhdhcmugew91ig5lzwqgdg8g': 79447,
 'q09qwsb5b3vyig93bibevkqgtw92awvzlg0kdqpodhrwoi8vc2ftlm1vdghv': 74345,
 'c3quy29tl3bvcy9kdmquahrtdqorkysrkysrkysrkysrkysrkysrkysrkysr': 26125,
 'kysrkysrkysrkysrkysrkysrkysrkysrkysrkysrkysrkysrkysrkysrkysr': 56982,
 'kysrkysrdqpuaglzigvtywlsighhcybizwvuihnjcmvlbmvkigfuzcbmawx0': 56974,
 'zxjlzcbiesbvdxigaw4gag91c2ugiijpufqtt1vuiiigc3lzdgvtigluia0k': 101091,
 'y29tcgxpyw5jzsb3axroihn0yxrligxhd3muielmihlvdsb3axnoihrvicjp': 97861,
 'ufqtt1vuiibmcm9tihroaxmgbwfpbgluzybhcyb3zwxsia0kyxmgdghligxp': 89816,
 'c3rzig9mihrob3vzyw5kcyagb2ygb3rozxigzw1hawwgchjvdmlkzxjzihbs': 26134,
 'zwfzzsb2axnpdcagdqoncmh0dha6ly9zyw0ubw90ag9zdc5jb20vcg9zl29w': 100946,
 'dg91dgquahrtba0kkysrkysrkysrkysrkysrkysrkysrkysrkysrkysrkysr': 33562,
 'kysrkysrkysrkysrkysrkysrkysrkysrkysrkysrkysrkysrkysrkysrkw0k': 56981,
 'odqyovplwm01ltu4ngjsyw4yodi2enhhrdetmtm4qm1uvdywothuswnvny0y': 66968,
 'mjbyawtnmzyymgw1mg': 62329,
 'multipart': 63568,
 'reader': 76525,
 'understand': 90439,
 'legible': 57903,
 'xx9adb9a99': 97661,
 '1a5b9adbxx': 2916,
 '7bit': 11547,
 'k1': 55200,
 'erotikverlag': 39034,
 'sucht': 84813,
 'pornodarsteller': 72407,
 'wenn': 95034,
 'du': 36325,
 'spaß': 83355,
 'sex': 81336,
 'hast': 46711,
 'und': 90385,
 'nebenbei': 64629,
 'geld': 44153,
 'verdienen': 92286,
 'willst': 95427,
 'bewirb': 23148,
 'auch': 20759,
 'dich': 33878,
 'wir': 95533,
 'suchen': 84811,
 'natürliche': 64403,
 'frauen': 42664,
 'männer': 64010,
 'jeden': 54007,
 'alters': 18775,
 'mollig': 62726,
 'kein': 55713,
 'problem': 73183,
 'infos': 51821,
 'unter': 90851,
 '0930': 863,
 '830': 12212,
 '13': 2065,
 '22': 3953,
 'aus': 20838,
 'österreich': 102335,
 '01': 307,
 '90': 13531,
 '87': 12694,
 '54': 9139,
 'deutschland': 33438,
 '86': 12603,
 'eu': 39312,
 'min': 62076,
 'callcenter': 26473,
 'hier': 47445,
 'ein': 37850,
 'bild': 23542,
 'einer': 37855,
 'produktion': 73259,
 'das': 32254,
 'vorstellungsvideo': 93105,
 'siehst': 81927,
 'web': 94830,
 'darsteller': 32249,
 'php': 71273,
 'solltest': 83022,
 'unserem': 90793,
 'newsletter': 64980,
 'interesse': 52278,
 'mehr': 61411,
 'haben': 46358,
 'dann': 32207,
 'trage': 88381,
 'bitte': 23684,
 'newsletr': 64979,
 'image': 51080,
 'jpeg': 54705,
 'disposition': 34366,
 'attachment': 20660,
 'filename': 41474,
 'lenkawolfgangk1': 57957,
 '9j': 14220,
 '4aaqskzjrgabageasabiaad': 8354,
 '4rr': 8754,
 'rxhpzgaasukqaagaaaajaa8bagafaaaaegaaabab': 79539,
 'agamaaaagaaaabibawabaaaaaqaaabobbqabaaaajaaaabsbbqabaaaalaaaacgbawabaaaa': 17685,
 'agaaadibagauaaaanaaaabmcawabaaaaagaaagmhbaabaaaasaaaapgbaabtt05zaabeq1it': 17679,
 'uemxmtbfiabiaaaaaqaaaegaaaabaaaamjawmjowndoxnyaxodoymdo1oaarajqcbqabaaaa': 89765,
 'ggeaaj2cbqabaaaaigeaackiawabaaaaagaaaacqbwaeaaaamdixmaoqagauaaaakgeaaasq': 44438,
 'agauaaaapgeaaagrbwaeaaaaaqidaakrbqabaaaaugeaaasscgabaaaawgeaaawsbqabaaaa': 17690,
 'ygeaaamsawabaaaaaqaaaaqsbqabaaaa0geaaacgbwaeaaaamdewmaggawabaaaaaqaaaaog': 98428,
 'baabaaaagaqaaakgbaabaaaayamaaawgbaabaaaa2geaaaaaaaabaaaamgaaalqaaabkaaaa': 22060,
 'mjawmjowndoxnyaxodoymdo1oaaymdayoja0oje3ide4ojiwoju4aaiaaaabaaaaaaaaagqa': 62326,
 'aacqaaaazaaaacoaaaakaaaaagabaaiabaaaafi5oaacaacabaaaadaxmdaaaaaacgcgkgma': 16084,
 'aqaaaayaaaapaqiabqaaahycaaaqaqiadaaaahwcaaasaqmaaqaaaaeaaacgkguaaqaaaigc': 19860,
 'aacgkguaaqaaajacaacgkgmaaqaaaaiaaaayaqiafaaaajgcaacgkgqaaqaaak0caacgkgqa': 16079,
 'aqaaaesyaaaaaaaau09owqaarenslvbdmtewrsaasaaaaaeaaabiaaaaaqaaadiwmdi6mdq6': 19862,
 'mtcgmtg6mja6ntgaap': 63410,
 '8qbogaaaqubaqebaqeaaaaaaaaaaaecawqfbgcicqolaqadaqeb': 13364,
 'aqebaqebaaaaaaaaaqidbaugbwgjcgsqaaibawmcbamfbqqeaaabfqecawaeequsitfbbhnr': 19885,
 'yqcicrqygzghccncscevuthwjdnicoijchyxgbkajsynkckqndu2nzg5okneruzhselku1rv': 98903,
 'vldywvpjzgvmz2hpann0dxz3ehl6g4sfhoeiiyqsk5svlpeymzqio6slpqeoqaqys7s1tre4': 92926,
 'ubrcw8tfxsfiycrs09tv1tfy2drh4upk5ebn6onq8flz9px29': 89609,
 'j5': 53567,
 'heaagecbaqdbacfbaqa': 46942,
 'aqj3aaecaxeebsexbhjbuqdhcrmimoeifekrobhbcsmzuvavynlrchyknoel8rcygromjygp': 19898,
 'kju2nzg5okneruzhselku1rvvldywvpjzgvmz2hpann0dxz3ehl6gooehyahiimkkpoulzax': 56178,
 'mjmaoqokpaanqkmqsro0tba3ulm6wspexcbhymnk0tpu1dbx2nna4upk5ebn6onq8vp09fb3': 62349,
 'pn6': 72111,
 '9sahaagbaqfbamgbqqfbgygbwkpcqkicaksdq0kdxutfhyvexuugbsihrgzibkufr4o': 14428,
 'hiajjcynjhccki0qjs0ijsylaqygbgkhcrejcrelgbuyjsuljsuljsuljsuljsuljsuljsul': 47420,
 'jsuljsuljsuljsuljsuljsuljsuljsuljsuljsx': 54813,
 'waarcab4akadaseaahebaxeb': 93818,
 '9oadamb': 14323,
 'aairaxeapwdxxttxvjahwmda6ohvovs4jyz9zxmvyxpbo1gtcg31e3l1mapu': 16153,
 'ymmsb8v': 98690,
 'en5': 38377,
 '1u6pmsnwys4ow7pbi4': 3312,
 'pwu4umbg0jpyz1ee8zkdz5yk7dspbncb2xxpjagyeuhzuwg3aoums': 74195,
 'i6jlajrae': 48949,
 'fczoxbgclzyzclpno6e1q6paryqpd2cu2rovyf5': 40902,
 'otquuwskjkrftg4my': 68257,
 'cnim': 29011,
 'tu9rutj1liodrtjnkfklxgc4zqstx0iyfrzgdyqz719': 88906,
 'hqqru1nh5xjslldvnbrreqom54qr': 48296,
 'ywc': 99163,
 'yrosct3f8skh2ppqey4h5u7d6jdcp8kgkhgektrsnfs5tlh45qhcqdcgvm0ao8gvordu': 98947,
 'myw0kup45u': 63940,
 'maeme4': 60165,
 'lv9m0dw9qjkk0maxuct7dukvtnge5apb86': 59692,
 'xw9kvsxifdyuvglh2vq': 97621,
 'nu9b8q2dq8s2koillr2mycedp4vf9am0zvpqhjuims6vgwtussofxzuyndolvugdxka': 66118,
 'z0pq': 99453,
 'dkz8hbgeeiur0q': 34609,
 'cljpi4zxnswh6idmbdvmjtng': 28739,
 '9wehdseat64rkmrhft1k95pysrkfr06y': 14524,
 'rnnr0h4kcw7mljoov': 78652,
 'klcttnjxtpjvidb3fvjb6tbloly1caupwchowpfb6fu10phv402e0e': 56243,
 'cxiob7wccgejs8tdhuj7w57agvrmuxkpxs6hxgc4f1z8y': 31585,
 'i7gp4gehzfhk3wku87o4nyh8hv': 48965,
 'u18zajcsbfvuritjzvap9wafeuszscuw5888rxci5cuhsiqbcjbhr60ez6d3xxucdtwo0seq': 89351,
 'ffrsbieldeveehwkjbhiqplcsc4rnmit0pmhliw2mas3k2nycy9wfrzivzpadsbtw1anif8y': 41284,
 '7zo': 11964,
 '3opm6f8aju38q8bcx9': 7580,
 'mppce37fo1rhulguo5e3ip3yp0rnblwtanieosumurr5jllg8': 63146,
 'kjkjr0pbvtzt3kfotzpjhz1vtez1omubyrfxuay7ipy7hkvzubih3vavmou61prqitlq6ds7': 56162,
 'vda7ww': 92111,
 'ot2wkdigz1rnqbnbh3dalivs5aqpewxnw7s': 68186,
 'rgvitztstjzfxloswoajdqmo3ldti': 78161,
 'hp0': 48234,
 'lxhe9pnbneqedr': 59782,
 've1gz3jznz2z0': 92150,
 'etrp': 39295,
 'fl82fic3dmrhi2w': 41778,
 '8aaup54': 12883,
 'kvupsmyiuy': 56857,
 'juln': 54920,
 'wdxwmidmmicdhmi0zc8eahndetato29nplhz': 94775,
 'caqcb7c5x9a7inpxx0eaqqdfer': 26683,
 '8dnghdhetrqg8c4zsmw9dxzc8nltqvnpuc1vli5ytumqlvofmuwzsd4w568': 13092,
 '0r3ycflsvyyh': 1270,
 'tshcqbxgv5mewjpex89bcuhkju09cj': 88810,
 'x3p8ajwynvgh8yywrylvesd': 96634,
 'oannffdsrjgo4la9': 66650,
 'gbf1ojxbgwpfmtlhgbjpqivmyah11tyl2nb7w02b9yliv': 43976,
 'ma6nry0kyyc81z1xdtnxh42snp': 60071,
 'uxpiptoaztyvbfbsukz9otydtv2rwer3xnztrkc15b4y0ott5fvlrcrjeigcc8z': 91530,
 'xfenhz8j': 97004,
 'pixtp2ktmjvikg': 71614,
 '07tfjujzrnbjpb04r22k2kntlesmfo54lmj2keft0': 764,
 'vfpnoa68stjky9t': 92412,
 'xrssln0': 97450,
 'xrp7ti8yllglcakqrjpftxoo4qevppivyyh': 97447,
 'u2fn8srarr9a3k9p1pcf9od8k9dn': 89390,
 'zifyhkhb': 100176,
 'y1wmxipzv2j5ttlzl': 97840,
 'wlw1h7stzkm4ypdedopsvegoljobnagoa8vb': 95709,
 'c7nu49xk': 26258,
 'mhs8ht7k7luqxworxuhbitjptxh6n4cfwii5bk6wg7tjaz': 61828,
 '48889': 8283,
 'v8am1ljpu6xq3yuknfz': 91804,
 'w5shtxny3c23lw12p43iucj15of0runi0magfztukjmrdjjt7opp714ojlchwn0': 93694,
 'ehuqay2n': 37795,
 '21hnxiooowfdbo9qqbuazxnm9wghox00dradrkx74rintvpmznmybc0kttsurxmiv4hj2eh3': 3944,
 'rf1i0kut8awirgrkbcp24pbhbbzgmuml5wrnhjod0jxvvhpbqmltdbd0dfcbaufcgetxp': 78059,
 'ikexw1bvjkiv94eqezb57qacc9m46ele0oxqk7pnqlsdctjf2l2n': 50955,
 'evxdzcjz7io9wjww': 39500,
 '0o': 1200,
 'gy4ycfup69yegxxkh0rw18v9k1q5sc6xytvxsmybw64afpnp1xnparuwu40w49zysypzxmvo': 46049,
 '92julkuocmyoldixjivzufo630inoeocagl79kllbngxgmwwfx3zhozjffulb': 13656,
 'zwpwf': 100984,
 'tte': 88850,
 'wsnjibgzujhxv': 96198,
 '8arry8nfl1pcxqtnwcoqh14z87dr2inc6dk86': 12992,
 'eoxublnrbwkkbfx1xx69': 38784,
 'ugqcc4qp80kvlxtalzu4m6btdnhs4wetjxyxjyfxrrebkkhphrxym5ours': 89865,
 '9hfu4pwnvt0wo': 14194,
 'juzrnv7vpi': 54999,
 'wbcf6j0oagvzoe8qeklwxthmuz1rvbjlngcvp7bx28vajg4vf7plhasik': 94250,
 'dgk': 33656,
 'e4bgpyh646vvsotpztsyva6t5u9wdxa': 36914,
 'hbyijrrfvv94xxtoggpphimftuaa1j7by7q7vysm': 46831,
 'c1lktk9twnt5fc8m8f8ah': 25969,
 'ahwbi': 18041,
 'hv2lmgxopx8h': 48597,
 'tcyrg4ne7hmuri': 86419,
 'cx0f3jyousqfbjpt': 31573,
 'fxlsydomnkq': 43390,
 'wvxt': 96343,
 'tdbxo7nwb4': 86427,
 'ftduh0m': 43056,
 'newwkxhe0g': 65007,
 'ae9ap93t7celexekdgdh1r1cj': 17372,
 'ucowfq8lmqkjuuupgssfuj86gkzjoppmulnf5i8o': 89662,
 'gvpkx98yjazlcjdqmcsppytd7ip3abj': 45953,
 'o1': 66463,
 '58f1rhofaj0sy26rbm6e7kullrszjxb': 9358,
 'esj': 39138,
 'hpye': 48271,
 'pxt9emrp9mkkbexaahqv4gav': 74232,
 'at5': 20561,
 'ex9xkmg9ls5735jwwmigweb3fvpnsigyhyplpijryurs9utsiteel7sytwlxesuqkhxkcgn3': 39575,
 'pncpr3xcs4y2j07nxiom3hfz': 72125,
 'wak6awgln7hhwxcaa1z5lrfik': 93941,
 '165ml7m2zpyxg': 2481,
 'kp8ttvd': 56521,
 'ic60k9wse': 49246,
 'zfu3neeh9x6hhevw9jfq5tw3ijyqc5714z8twahp8ciklxueg84zxtryjonyn': 99984,
 'u9jxh1kfljn0': 89520,
 'hrc0dpv9otzxi4hsqehhlz19q828c': 48314,
 'dmyng17oqot0cslziy3mgdquohgd': 34713,
 'ix3rbd13tl5gwjwarrbw550lwc0leujv5yvgov2lsmzbz0of5vx1c': 53344,
 'exc242lnccdhp07fhx': 39608,
 'tppq6pmpkuhytaooz5zx0x4m1itwfblhd3opoaik5ypmzecfx612ysturhnzgk6d': 88258,
 'pshgseu': 73665,
 'agm56hmvtpe3oh8f6euneerrcq': 17787,
 'zovnur3lcjpubgfhwlqf81vz': 100532,
 'xcqzptttodvctj2': 96901,
 'hkiv': 47673,
 'ok1tpe8es054iyv9r2l2qwxge': 67313,
 'wpuk': 96035,
 '9bmdxfemd3svk6jcmfdu0oxstjn1fxjbwvs7szbqv': 14055,
 'oc15jrnjdunvu': 66807,
 'krkq2cmojzvok68hhnufm9jkx2kjrjzpuzj4s1u6tpbuepjqzbzjburl': 56631,
 'tdhv752fpaysberaya': 86434,
 'p6cvalra0spmo14zu7lwsn4zwjkbv1jbb6iku4py': 68923,
 'wsmrgyd1c9f': 96196,
 'feqyg': 41111,
 'ks2a8kdi56z7fnk': 56666,
 '8a6q9hsrt4pyi4ymv42tdiuduf7o9cz5ioosmhbhjypl2jpo8v': 12858,
 'b9khlun7dkvbwyxyk7yktgppbo5gnqkgnjcrnbhrvaxubbps15njpfbwqxawsngbbyqmdkya': 22030,
 '78': 11412,
 'lxk4t2uepgrgmzkl2pnrxtq0wrellu': 59785,
 'timhjlcekecoaog4htpwotk5ne9sg4wuwfiyia': 87527,
 'nvlnbmk9v': 66252,
 'fuppgkjor5cjj655z': 43235,
 'tdue': 86448,
 'ihm49r2r2icevwo3cbesk9u8rlqzegsnh5msu6f': 50596,
 'drhtpkwkwuepla': 36132,
 'jwk8jh39joe7lt': 55064,
 '2juu21whicobnh0pl3p2p3mbn5smc44osx': 5283,
 'hp': 48233,
 'ovmz': 68581,
 'nrep9nbnrq4zwvcf5exivd3szrbvnyudoz1a9a6bqnh0': 65941,
 'wsnxtkvumeyfvt9t': 96200,
 'svosqrqqrt': 85241,
 '1plc8ovacua': 3236,
 'j69vikhj3ysrtyrkc': 53594,
 'apxqvlk3hsraxrlhefwfar1mkz55nphnfidwtbid': 19841,
 '5rg4jucyj8twfy5': 9807,
 't9k5cwcrxi26rmrmchcc5rza8fg7r7ofnkolfntpg3whb6daryxdkzmb': 85890,
 'nydgn': 66356,
 'tdnbewkjevuxaxx6y6v83vl7sxmfz4ehsykjpxxuuntsjxcr90sst36k5pf8k5pxpb': 86441,
 '6lrukgzs2abdihkhusy5aphi3y7jp71ejjsuzoqxbg0jydx': 10765,
 'aahqelwcn08erk3yyyajtgme': 16139,
 'zxwopdupfa3khaqsdng49': 101148,
 'wr2iyilr81uwc09ilbqebfxqyeqgcktjoofsvotw7zwaboce': 96075,
 'foynefbda8hpevvwdm7nizjgshy2nivwcdv50x2': 42504,
 'h8a9bni3b3muhbyc88c1hejtfutrmn1p': 46296,
 'k3sgdhb7sgomqfy': 55269,
 'z1hfwhzxselqm6cljmydn8unfemy1qnrc': 99462,
 'xd8k59v88': 96918,
 'prtdo1jz': 73611,
 'kayhhgayof1r5jfuhcvmfz4lfrqxttniwstjcamgqfx4czbg3fowhkbgkdghor3rlo1pujqu': 55543,
 'wdteldeqczk5lywd5zxo': 94742,
 '6hjtnlxant6dfyzu6ssgoxsnocdq': 10688,
 'tweohil2fy': 89122,
 'gzhlz4kv0rx': 46101,
 '5mlqelqjhlnoszcnjldqo9fvdvpxdxfldxatbjasorricjmflvgeoj6jiqxmlozwds0rs9': 9702,
 'c07xdd2sywvimwo80e27qq43gyycpzz06hvw95nnc2q3elphktnglso': 25936,
 'hr5ert5hpsfeyapz': 48307,
 'x13j4nwksz5d3kggmb17': 96552,
 'wolrxjzqxsvq0ymwxgivjpvwxs3j6hv7anon2xzbuylhlssky4x': 95827,
 'g8jka9porxjei9v0': 43638,
 'wswl7y0parocx7diqpxd7gfwuwuc5lwl4uund1oxvlyjo7dw': 96219,
 'tkndn': 87692,
 '9avqtgmbsb3': 14034,
 'z7gh7pmx8knpyn': 99618,
 'f1r18nxvksr': 40212,

In [12]:
X_train, X_test, y_train, y_test = train_test_split(all_features,data.CATEGORY, 
                                                   test_size=0.3, random_state=88)

In [13]:
X_train.shape

(4056, 102512)

In [14]:
X_test.shape

(1739, 102512)

In [15]:
classifier = MultinomialNB()

In [16]:
classifier.fit(X_train, y_train)

MultinomialNB()

In [17]:
nr_correct=(y_test == classifier.predict(X_test)).sum()

In [18]:
print(f'{nr_correct} documents classified properly')

1624 documents classified properly

In [19]:
nr_incorrect = y_test.size - nr_correct

In [20]:
print(f'Number of documents classified is {nr_incorrect}')

Number of documents classified is 115

In [21]:
fraction_wrong = nr_incorrect / (nr_correct + nr_incorrect)
print(f'The (testing) accuracy of the model is {1-fraction_wrong:.2%}')

The (testing) accuracy of the model is 93.39%

In [22]:
 classifier.score(X_test, y_test)

0.933870040253019

For the testing dataset calculate the recall, precision and f1 score. Google for the scikit learn documentation on this topic to work it out.

In [23]:
recall_score (y_test, classifier.predict(X_test))

0.809009009009009

In [24]:
precision_score (y_test, classifier.predict(X_test))

0.980349344978166

In [25]:
f1_score(y_test, classifier.predict(X_test))

0.8864758144126358

In [26]:
example = [
    'get viagra for free!',
    'need a mortgage? Reply to arrange a call with a specialist and get a quote',
    'Could you please help me with the project for tomorrow?',
    'Hello Jonathan, how about a game of golf tomorrow?',
    "Ski jumping is a winter sport in which competitors aim to achieve the longest jump after descending from a specially designed ramp on their skis. Along with jump length, competitor's style and other factors affect the final score. Ski jumping was first contested in Norway in the late 19th century, and later spread through Europe and North America in the early 20th century. Along with cross-country skiing, it constitutes the traditional group of Nordic skiing disciplines."
]

In [27]:
doc_term_matrix = vectorizer.transform(example)

In [28]:
classifier.predict(doc_term_matrix)

array([1, 1, 0, 0, 0])